Gem::Specification.new do |s|
  s.name        = 'spaceship_stub'
  s.version     = '0.0.3'
  s.date        = '2017-07-13'
  s.summary     = 'Rails gem for stubbing out Fastlane::Spaceship for writing specs'
  s.description = 'stubbing out Fastlane::Spaceship for writing specs'
  s.authors     = ['Minh Luong']
  s.email       = 'en14vn@gmail.com'
  s.files       = [
    'lib/spaceship_stub.rb',
    'lib/spaceship_stub/tunes_stubbing.rb',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/app_details.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/app_overview.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/app_overview_stuckinprepare.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/app_pricing_intervals.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/app_resolution_center.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/app_resolution_center_valid.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/app_submission',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/app_summary.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/app_version.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/app_version_ref.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/app_version_states_history.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/app_versions_history.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/availability/add_request.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/availability/add_response.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/availability/remove_request.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/availability/remove_response.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/availability/uninclude_all_future_territories_request.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/availability/uninclude_all_future_territories_response.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/build_details.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/build_history.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/build_history_for_train.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/build_trains.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/build_trains_operation_failed.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/candiate_builds.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/create_application_broken.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/create_application_first_broken.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/create_application_prefill_first_request.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/create_application_prefill_request.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/create_application_success.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/create_application_wildcard_broken.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/create_sandbox_tester.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/create_sandbox_tester_payload.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/create_version_success.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/delete_sandbox_tester.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/delete_sandbox_tester_payload.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/iap_consumable_template.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/iap_create.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/iap_detail.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/iap_families.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/iap_family_create.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/iap_family_create_success.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/iap_family_detail.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/iap_family_edit.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/iap_family_edit_versions.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/iap_family_template.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/iap_list.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/iap_price_goal_calc.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/iap_pricing_tiers.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/iap_update.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/invalid_login.html',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/landing_page.html',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/login_cntrl.js',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/login_cookie_spam.txt',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/member_create.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/member_create_appmanager_single_app.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/member_create_developer.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/member_list.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/member_template.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/pricing_tiers.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/promocodes.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/promocodes_generated.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/promocodes_history.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/ratings.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/ratings_US.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/reject_app_version_success.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/review_by_storefront.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/sandbox_testers.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/supported_countries.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/testers/create_tester.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/testers/existing_internal_testers.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/testers/get_external.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/testers/get_internal.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/testflight_build_info_appletvos.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/testflight_build_info_ios.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/testflight_submission_submit_appletvos.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/testflight_submission_submit_ios.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/update_app_version_failed.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/update_app_version_success.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/update_app_version_temporarily_unable.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/update_app_version_with_autorelease_overwrite_success.json',
    'lib/spaceship_stub/spaceship/spec/tunes/fixtures/user_detail.json',
  ]
  s.required_ruby_version = '~> 2.0'
  s.homepage    = 'https://github.com/luongm/spaceship_stub'
  s.license       = 'MIT'
end
